#!/usr/bin/env python
from email.mime.text import MIMEText
import smtplib
from time import sleep

import click
import requests


def _get_ip():
    r = requests.get('http://ifconfig.co/ip')
    r.raise_for_status()
    return r.text.strip()


def _save_ip(ip_file, ip):
    with open(ip_file, 'w') as f:
        f.write(ip)


@click.command()
@click.option(
    '--username',
    envvar='WATCH_IP_USERNAME',
    help='The username to send emails from.',
    required=True,
)
@click.option(
    '--password',
    envvar='WATCH_IP_PASSWORD',
    help='The password for the email username.',
    required=True,
)
@click.option(
    '--ip-file',
    envvar='WATCH_IP_FILE',
    help='The file to store the current IP',
    required=True,
)
def main(username, password, ip_file):
    s = smtplib.SMTP('smtp.gmail.com', 587)
    s.starttls()
    s.login(username, password)

    try:
        with open(ip_file) as f:
            ip = f.read()
    except FileNotFoundError:
        while True:
            try:
                ip = _get_ip()
                break
            except requests.HTTPError as e:
                if e.response.status_code != 429:
                    raise
                sleep(60)

        _save_ip(ip_file, ip)

    while True:
        sleep(120)  # every 2 minutes
        try:
            new_ip = _get_ip()
        except requests.HTTPError as e:
            if e.response.status_code != 429:
                raise
            # don't overload ifconfig.co's servers
            continue

        if new_ip != ip:
            text = f'Combine server IP address changed to: {new_ip}'
            msg = MIMEText(text)
            msg['To'] = username
            msg['From'] = username
            msg['Subject'] = text
            s.send_message(msg)
            ip = new_ip
            _save_ip(ip_file, ip)


if __name__ == '__main__':
    main()
